src/Form/InscriptionType.php
<?php

namespace App\Form;;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;

/**
 * Class InscriptionType.
 */
class InscriptionType extends AbstractType
{

    /*private $class;

    public function __construct($class)
    {
        $this->class = $class;
    }*/
  
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'personType',
                ChoiceType::class,
                array(
                    'label' => 'form.person_type',
                    'choices' => array_flip(User::$personTypeValues),
                    'expanded' => true,
                    'empty_data' => User::PERSON_TYPE_NATURAL,
                    'required' => true,
                    //'choices_as_values' => true
                )
            )
            ->add(
                'companyName',
                TextType::class,
                array(
                    'label' => 'form.company_name',
                    'required' => false,
                )
            )
            ->add(
                'lastName',
                TextType::class,
                array(
                    'label' => 'form.last_name',
                )
            )
            ->add(
                'firstName',
                TextType::class,
                array(
                    'label' => 'form.first_name',
                )
            )
            ->add(
                'phonePrefix',
                HiddenType::class,
                array(
                    'label' => 'form.user.phone_prefix',
                    'required' => false,
                    'empty_data' => '+33',
                )
            )
            ->add(
                'phone',
                TextType::class,
                array(
                    'label' => 'form.user.phone',
                    'required' => true,
                )
            )
            ->add(
                'email',
                TextType::class,
                array('label' => 'form.email')
            )
            ->add(
                'plainPassword',
                RepeatedType::class,
                array(
                    'type' => PasswordType::class,
                    'options' => array('translation_domain' => 'cocorico_user'),
                    'first_options' => array(
                        'label' => 'form.password',
                        'required' => true,
                    ),
                    'second_options' => array(
                        'label' => 'form.password_confirmation',
                        'required' => true,
                    ),
                    'invalid_message' => 'fos_user.password.mismatch',
                    'required' => true,
                )
            );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => User::class,
                'csrf_token_id' => 'user_registration',
                'translation_domain' => 'cocorico_user',
                'validation_groups' => array('CocoricoRegistration'),
            )
        );
    }

    /**
     * BC
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'user_registration';
    }
}

templates/recherche/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resultats de votre recherche - {{parent()}}{% endblock %}

{% block body %}

<style media="screen">
    /* Mariages */
    .lead a {
        color: #665600;
    }

    li a {
        color: #665600;
    }

    .card-header {
        background-color: #cab437;
        color: #fff;
    }

    .card-mariages .card-body {
        max-height: 350px;
        overflow-y: auto;
        margin-top: 20px;
        background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAUCAMAAAB70KeTAAAADFBMVEX29vb7+/v////y8vIBesvrAAAAEklEQVR4AWNggkJGJIgAzDAIAAIvAB5vqnzBAAAAAElFTkSuQmCC) repeat-x left bottom;
        border: 1px solid #d9d9d9;
    }

    .card-mariages .list-group-item {
        background-color: transparent;
        border: 0;
        padding: 0 0 5px 0;

    }

    .card-mariages .label_card_mariages {
        font-weight: 600;
        padding-bottom: 10px;
    }

    .card-mariages label {
        margin-bottom: 0;
    }

    .themeBtn {
        background: #cab437;
        color: #ffffff !important;
        display: inline-block;
        font-size: 15px;
        font-weight: 500;
        height: 40px;
        line-height: 0.8;
        padding: 14px 30px;
        text-transform: capitalize;
        border-radius: 1px;
        letter-spacing: 0.5px;
        border: 0px !important;
        cursor: pointer;
        border-radius: 100px;
        margin-bottom: 5px;
    }

    .themeBtn:hover {
        background: #fff;
        color: #cab437 !important;
        box-shadow: 0 10px 25px -2px #cab437;
    }

    .titlemariages {
        font-family: Merriweather, "Times New Roman", Times, serif;
        font-size: 30px;
        line-height: 42px;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        font-weight: 700;
        margin: 10px 0;
        color: #222 !important;
    }

    .stitlemariages {
        font-size: 16px;
        line-height: 24px;
        margin: 0 40px 15px;
        color: #222 !important;
    }

    /* Pagination */
    .pagination>li>a { border-radius: 50% !important;margin: 0 5px;}

    .pagination {
    justify-content: center;
    margin-bottom: 20px;
    }

    .page-item.active .page-link {
    color: #fff;
    background-color: #cab437;
    border-color: #cab437;
    }

    .page-link {
    color: #cab437;
    }

    .page-link:hover {
    background-color: #cab437;
    color: #fff;
    }
</style>
<!-- Page Content -->
<div class="container">
    <div class="col-12">
        <h1 class="text-center text-secondary titlemariages">Résultats de votre recherche</h1>
    </div>
    <div class="col-12 text-center pb-4 mb-4">
        <span class="text-secondary stitlemariages">
            {% if recherche is not empty %}
                {{recherche}} 
            {% else %}
                Tous les prestataires
            {% endif %}

            {% if lieu is not empty %}
                à {{lieu}}
            {% else %}
                partout en France
            {% endif %}
        </span>
    </div>

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-lg-8">
			{% if erreur == null %}
				<div class="container">
					<div class="row block_2  m-0 p-0">

						{% for l in listings %}
							<div class="col-md-4 col-lg-4 cardwedding">
								<div class="card card-inverse card-info">
									<a href="{{path("listing", {"url": l.translation[0].slug})}}">
										<img src="../images/{{l.ListingImage[0].name}} " alt="" class="card-img-top" />
									</a>
									<div class="card-block">
										<figure class="profile">
											<img class="profile-avatar" src="../images/{{l.user.images[0].name}}" alt="Assa" />
											<a href=""></a>
										</figure>
										<p class="categorycard">{{l.ListingCategory[0].listingCategoryTranslations[0].name}}</p>
										<h4 class="card-title mt-3 titlecard">
											<a href="{{path("listing", {"url": l.translation[0].slug})}}">{{l.translation[0].title}}</a>
										</h4>
										<div class="meta card-text locationcard text-center">
											<span><i class="fa fa-map-marker" aria-hidden="true"></i>{{l.location.city | capitalize}}</span>
										</div>

									</div>
									<div class="card-footer text-center">
										<p class="nameprixcard">Prix de location:</p>
										{% if l.price is defined and l.price > 0 %}
											<p class="prixcard">{{l.price}} €</p>
										{% else %}
											<p class="prixcard">Sur devis</p>
										{% endif %}
									</div>
								</div>
							</div>
						{% endfor %}

					</div>
				</div>
				<!-- Pagination -->
				<div class="row">
					<div class="col-md-12">
						<nav aria-label="Page navigation example">
						<ul class="pagination">
							<li class="page-item">
								<a class="page-link" href="#" aria-label="Previous">
									<span aria-hidden="true">«</span>
									<span class="sr-only">Previous</span>
								</a>
							</li>
							<li class="page-item active"><a class="page-link" href="#">1</a></li>
							<li class="page-item"><a class="page-link" href="#">2</a></li>
							<li class="page-item"><a class="page-link" href="#">3</a></li>
							<li class="page-item">
								<a class="page-link" href="#" aria-label="Next">
									<span aria-hidden="true">»</span>
									<span class="sr-only">Next</span>
								</a>
							</li>
						</ul>
						</nav>
					</div>
            	</div>
            <!-- Fin pagination -->
			{% else %}
				<h1>{{erreur}}</h1>
				<a href="#">Retour à l'accueil</a>
			{% endif %}
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Search Widget -->
            <div class="card card-mariages shadow border-0">
                <h5 class="card-header">Types de prestataires</h5>
                <div class="card-body">
                    <ul class="list-group">
                        <span class="label_card_mariages">Tous les types</span>
                        <li class="list-group-item rounded-0">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="all">
                                <label>Tout cocher</label>
                            </div>
                        </li>
                        <li class="list-group-item rounded-0">
                            <hr>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="text-center p-2 m-2">
                <input type="submit" value="Rechercher" name="btRechercher" class="btn btn-default" style="color: #fff;background-color: #cab437;padding: 10px 20px;text-transform: uppercase;border-radius: 45px;font-size: 14px;border: 1px solid #cab437;">
            </div>

            <hr>

            <!-- Archives Widget -->
            <div class="card my-3">
                <h5 class="card-header">Trier</h5>
                <div class="card-body">
                    <ul class="list-unstyled mb-0 text-center">
                        <li>
                            <button href="https://www.behance.net/sakiran" target="_blank" class="themeBtn">Les plus récents</button>
                        </li>
                        <li>
                            <button href="https://www.behance.net/sakiran" target="_blank" class="themeBtn">Les plus anciens</button>
                        </li>
                        <li>
                            <button href="https://www.behance.net/sakiran" target="_blank" class="themeBtn">Les mieux notés</button>
                        </li>
                    </ul>
                </div>
            </div>


        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->
{% endblock %}